/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package code;

import javax.swing.ImageIcon;

/**
 *
 * @author Omar Romero
 */
public class usersearch extends javax.swing.JPanel {
    
    user useracc;
    
    public usersearch(user user) {
        initComponents();
        useracc=user;
        perfil.setText(user.username);
        this.followers.setText("Followers: "+user.followercount(user));
        this.following.setText("Following: "+user.followingcount(user));
        if(user.gender=='F'){
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/female.png"));            
            pfp.setIcon(icon);
        } else if(user.gender=='M'){
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/user.png"));   
            pfp.setIcon(icon);
        }
        if(useracc.followsuser(useracc)==true){
            follow.setText("Dejar de Seguir");
        }else{
            follow.setText("Seguir");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pfp = new javax.swing.JLabel();
        follow = new javax.swing.JButton();
        followers = new javax.swing.JLabel();
        following = new javax.swing.JLabel();
        perfil = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/otro.png"))); // NOI18N

        follow.setBackground(new java.awt.Color(29, 155, 240));
        follow.setForeground(new java.awt.Color(255, 255, 255));
        follow.setText("Seguir");
        follow.setBorderPainted(false);
        follow.setPreferredSize(new java.awt.Dimension(140, 23));
        follow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followActionPerformed(evt);
            }
        });

        followers.setForeground(new java.awt.Color(255, 255, 255));
        followers.setText("Followers: 0");

        following.setForeground(new java.awt.Color(255, 255, 255));
        following.setText("Following: 0");

        perfil.setBackground(new java.awt.Color(0, 0, 0));
        perfil.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        perfil.setForeground(new java.awt.Color(255, 255, 255));
        perfil.setText("Nombre Perfil");
        perfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        perfil.setContentAreaFilled(false);
        perfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pfp)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(followers, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(follow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(following))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pfp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(perfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(follow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(followers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(following)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void followActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followActionPerformed
        // TODO add your handling code here:
        
        if(useracc.followsuser(useracc)==true){
            follow.setText("Dejar de Seguir");
            useracc.unfollowacc(useracc);
        }else{
            follow.setText("Seguir");
            useracc.followacc(useracc);
        }
        followers.setText("Followers: " + useracc.followercount(useracc));
        following.setText("Following: " + useracc.followingcount(useracc));
        if(useracc.followsuser(useracc)==true){
            follow.setText("Dejar de Seguir");
        }else{
            follow.setText("Seguir");
        }
        
        
    }//GEN-LAST:event_followActionPerformed

    private void perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilActionPerformed
        // TODO add your handling code here:

        user u=new user();
        u.selectacc(useracc);
        accountframe frame = new accountframe(useracc);
        frame.setVisible(true);
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
        
    }//GEN-LAST:event_perfilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton follow;
    private javax.swing.JLabel followers;
    private javax.swing.JLabel following;
    private javax.swing.JButton perfil;
    private javax.swing.JLabel pfp;
    // End of variables declaration//GEN-END:variables
}
